---
title: "igem_part.Rmd"  
output: html_document

---

```{r echo=FALSE}
no <- c(1, 2, 3, 4, 5, 6)
team_name <- c("Tainan", "Valencia_UPV", "Vilnius-Lithuania", "William_and_Mary","Marburg", "Vilnius-Lithuania")
project_title <- c("Oh_My_Gut", "printeria", "SYN_ORI", "SPEED", "VIBRIGENS", "flavoflow")
project_year <- c(2019, 2018, 2017, 2017, 2018, 2020)
wiki_page <- c("https://2019.igem.org/Team:NCKU_Tainan", "http://2018.igem.org/Team:Valencia_UPV", "http://2017.igem.org/Team:Vilnius-Lithuania", "http://2017.igem.org/Team:William_and_Mary", "http://2018.igem.org/Team:Marburg", "https://2020.igem.org/Team:Vilnius-Lithuania")

igem_team <- data.frame(no, 
                        team_name, 
                        project_title, 
                        project_year, 
                        wiki_page)
#knitr::kable(std, format = "markdown")
knitr::kable(igem_team)
```

```{r echo=FALSE}
no <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28)

part_id <- c("BBa_K2259000", "BBa_K2259001", "BBa_K2259002", "BBa_K2259003", "BBa_K2259004", "BBa_K2259005", "BBa_K2259006", "BBa_K2259007", "BBa_K2259008", "BBa_K2259009", "BBa_K2259010", "BBa_K2259011", "BBa_K2259014", "BBa_K2259015", "BBa_K2259016", "BBa_K2259017", "BBa_K2259018", "BBa_K2259019", "BBa_K2259022", "BBa_K2259024", "BBa_K2259025", "BBa_K2259026", "BBa_K2259029", "BBa_K2259031", "BBa_K2259086", "BBa_K2259088", "BBa_K2259092", "BBa_K2259093")
part_name <- c("SynORI framework RNA II - Replication Initiator (Group A)",
               "SynORI framework RNA II - Replication Initiator (Group B)",
               "SynORI framework RNA II - Replication Initiator (Group C)",
               "SynORI framework RNA II - Replication Initiator (Group D)",
               "SynORI framework RNA II - Replication Initiator (Group E)",
               "SynORI framework RNA I - Plasmid replication Inhibitor (Wildtype)",
               "SynORI framework RNA I - Replication Inhibitor (Group A-GC)", "SynORI framework RNA I - Replication Inhibitor (Group B-GC)",
               "SynORI framework RNA I - replication Inhibitor (Group C-GC)",
               "SynORI framework RNA I - replication Inhibitor (Group D-NC)", "Rop protein - global copy number inhibitor (SynORI framework)",
               "Plasmid partitioning system (SynORI framework)",
               "Toehold 1 of SynORI selection system",
               "Toehold 2 of SynORI selection system",
               "Toehold 1 Trigger - SynORI selection system",
               "Toehold 2 Trigger - SynORI selection system",
               "Alpha-neomycin resistance protein",
               "Beta-neomycin resistance protein",
               "SynORI framework RNA I - Plasmid replication Inhibitor (Group E-NC)",
               "SynORI framework RNA I - Plasmid replication Inhibitor (Group A-NC)",
               "SynORI framework RNA I - Plasmid replication Inhibitor (Group B-NC)",
               "SynORI framework RNA I - Plasmid replication Inhibitor (Group C-NC)",
               "SynORI framework RNA I - Plasmid replication Inhibitor (Group D-GC)",
               "SynORI framework RNA I - Plasmid replication Inhibitor (Group E-NC)",
               "RNA I (Wildtype ColE1)",
               "ColE1 replicon (Deactivated RNA I, placed next to RNA II)",
               "Minimal base vector for SynORI system building",
               "SynORI base vector 2.0 insert")
part_type <- c("Prject", "Prject", "Prject", "Prject", "Prject", "RNA", "RNA", "RNA", "RNA", "RNA", "Coding", "RNA", "Regulator", "Regulator", "Regulator", "Regulator", "Coding", "Coding", "RNA", "RNA", "RNA", "RNA", "RNA", "RNA", "RNA", "Regulator", "Plasmid", "Temporary" )
team_id <- c(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)

igem_part <- data.frame(no,
                        part_id, 
                        part_name,
                        part_type, 
                        team_id)

knitr::kable(igem_part)

```
