---
title: "Promoter_2nd.Rmd"
output: html_document
---


```{r echo=FALSE}
id <- c(1)
team_name <- c("Tongji_China")
project <- c("Seek Heme And Reflect cracK (SHARK)")
year <- c(2020)
wiki <- c("https://2020.igem.org/Team:Tongji_China")

igem_team <- data.frame(id, 
                        team_name, 
                        project, 
                        year, 
                        wiki)
knitr::kable(igem_team)
```
```{r echo=FALSE}
id <- 1:4
BBid <- c("BBa_R0051", "BBa_B0034", "BBa_E1010", "BBa_B0015")
type <- c("Promoter", "RBS", "RFP", "Terminator")
link <- c("http://parts.igem.org/Part:BBa_R0051",
           "http://parts.igem.org/Part:BBa_B0034",
           "http://parts.igem.org/Part:BBa_E1010",
           "http://parts.igem.org/Part:BBa_B0015")
backbone <- rep("pSB1C3", length(id))
device_id <- rep("-", length(id))
team_name <- rep("Tongji_China", length(id))
user <- rep("seokjin-oh", length(id))

igem_part <- data.frame(id, BBid, type, link, backbone, device_id, team_name, user)
knitr::kable(igem_part)
```


```{r echo=FALSE}
id <- 1:3
Promoter <- c("R0051", "J04450", "WT")
value <- c(195.6, 47, 1)
valunit <- rep("Fluorescence", length(id))
incubhr <- rep("Overnight", length(id))
incubtemp <- rep("37℃", length(id))
device_id <- rep("-", length(id))
link <- c("https://2020.igem.org/Team:Tongji_China/Results",
           "https://2020.igem.org/Team:Tongji_China/Results", "https://2020.igem.org/Team:Tongji_China/Results")


igem_obs <- data.frame(id, Promoter, value,
                        valunit, incubhr, incubtemp,
                       device_id, link)
knitr::kable(igem_obs)
```
```{r echo=FALSE}
library(tidyverse)
```

```{r echo=FALSE}
igem_promoter <- igem_part %>% 
  left_join(igem_team, by="team_name") %>% 
  left_join(igem_obs, by="device_id")
  
igem_promoter
```

```{r echo=FALSE}
colnames(igem_promoter)

plot_data <- igem_promoter %>% 
  filter(BBid=="BBa_R0051") %>% 
  select(Promoter, value) %>% 
  mutate(Promoter=factor(Promoter))

ggplot(plot_data, aes(x=Promoter, y=value)) +
  geom_bar(stat="identity", position=position_dodge(width=0.5), width=0.4) +
  scale_fill_manual(values=c("#ce1212", "#4a47a3")) +
  theme_bw()
```






